pipeline:
  install:
    image: iknpx/archnode
    commands:
      - yarn
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  lint:
    image: iknpx/archnode
    commands:
      - yarn lint
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  build:
    image: iknpx/archnode
    environment:
      - WS_HOST=https://moviexapis.herokuapp.com
    commands:
      - npm install -g gulp
      - gulp environment
      - NODE_ENV=production npm run dist
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  deploy:
    image: iknpx/archnode
    secrets: [ SSH_HOST, SSH_KEY, SSH_PATH ]
    commands:
      - npm install -g gulp
      - gulp deploy
    when:
      branch:
        - master
      event:
        - push
