---
parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended

plugins:
  - import
  - jsx-a11y
  - react

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: 16.3
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - ./src
    webpack:
      config: "./webpack/index.js"

rules:
  jsx-a11y/click-events-have-key-events:
    - 0
  jsx-a11y/label-has-for:
    - 0
  jsx-a11y/no-static-element-interactions:
    - 0
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  no-tabs:
    - error
  react/jsx-indent-props:
    - error
    - 4
  react/jsx-indent:
    - error
    - 4
  react/prop-types:
    - error
    - ignore:
      - children
  semi:
    - error
    - always
