/**
 * Do not edit this file
 *
 * SSH_HOST : ssh host
 * SSH_KEY  : ssh key
 * SSH_PATH : ssh path
 */

const gulp = require('gulp');
const sftp = require('gulp-sftp');
const json = require('jsonfile');

const environment = 'src/core/environment.json';

const {
    WS_HOST,
    NODE_ENV,
} = process.env;

gulp.task('deploy', function () {
    return gulp.src('dist/*')
        .pipe(sftp({
            host: process.env.SSH_HOST,
            keyContents: process.env.SSH_KEY,
            remotePath: process.env.SSH_PATH,
            user: 'root',
            remotePlatform: 'unix',
        }));
});

gulp.task('environment', done => {
    const data = json.readFileSync(environment);

    if (WS_HOST) {
        data.WS.HOST = WS_HOST;
    }

    if (NODE_ENV && NODE_ENV === 'production') {
        data.DEBUG = false;
    }

    json.writeFile(environment, data, done);
});
